apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: dependency-watchdog-prober
  name: dependency-watchdog-prober-config
data:
  dep-config.yaml: |
    kubeConfigSecretName: "dwd-api-server-probe-secret"
    kcmNodeMonitorGraceDuration: 40s
    nodeLeaseFailureFraction: 0.6
    dependentResourceInfos:
      - ref:
          kind: "Deployment"
          name: "kube-controller-manager"
          apiVersion: "apps/v1"
        optional: false
        scaleUp:
          level: 0
        scaleDown:
          level: 1
      - ref:
          kind: "Deployment"
          name: "machine-controller-manager"
          apiVersion: "apps/v1"
        optional: false
        scaleUp:
          level: 1
          initialDelay: 30s
        scaleDown:
          level: 0
      - ref:
          kind: "Deployment"
          name: "cluster-autoscaler"
          apiVersion: "apps/v1"
        optional: true
        scaleUp:
          level: 2
        scaleDown:
          level: 0
