// Code generated by "stringer -type=operationType -linecomment"; DO NOT EDIT.

package scaler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[scaleUp-0]
	_ = x[scaleDown-1]
}

const _operationType_name = "scale-upscale-down"

var _operationType_index = [...]uint8{0, 8, 18}

func (i operationType) String() string {
	if i >= operationType(len(_operationType_index)-1) {
		return "operationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _operationType_name[_operationType_index[i]:_operationType_index[i+1]]
}
